# Generated by Django 2.0.3 on 2018-12-21 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_remove_book_page_lenth'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='page_length',
            field=models.IntegerField(default=100, max_length=5),
            preserve_default=False,
        ),
    ]
