# Generated by Django 2.0.3 on 2018-12-21 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_page_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='page_length',
        ),
    ]
